# Generated by Django 5.1.7 on 2025-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('DisplayIcon', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numGrams', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=300)),
                ('ingredients', models.CharField(max_length=300)),
                ('frontPicture', models.ImageField(upload_to='uploads/')),
                ('backPicture', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descrption', models.CharField(max_length=300)),
                ('frontPicture', models.ImageField(upload_to='uploads/')),
                ('ingredientsPicture', models.ImageField(upload_to='uploads/')),
                ('requester', models.CharField(max_length=30)),
                ('requestDate', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
