# Generated by Django 5.1.6 on 2025-04-02 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='descrption',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='requestDate',
            field=models.DateField(),
        ),
    ]
