# Generated by Django 5.1.6 on 2025-04-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_productrequest_requestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approve'), ('DD', 'Denied')], default='PD', max_length=30),
        ),
    ]
