# Generated by Django 5.1.6 on 2025-05-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='DisplayIcon',
        ),
    ]
