# Generated by Django 5.1.6 on 2025-05-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_pet_displayicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
