# Generated by Django 5.1.6 on 2025-05-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=32),
        ),
    ]
