# Generated by Django 5.1.6 on 2025-05-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
